### ISSUE TITLE
Missing <dita> tags in the dita document generated from a word document using the converter

### ISSUE THREAD

**Issue by puniththota** [oxygenxml/oxygen-resources-converter#36] opened 2020-07-27 12:23 UTC
The dita tags are missing in the dita document generated from the word document. This specifically happens when the word document has a content/text before a header in the beginning. This also causes an issue where the dita document can not be opened in Author mode in the editor. 
[WordDocument.docx](https://github.com/oxygenxml/oxygen-resources-converter/files/4981950/WordDocument.docx)
[WordDocumentDitaOutput.zip](https://github.com/oxygenxml/oxygen-resources-converter/files/4981954/WordDocumentDitaOutput.zip)

**Comment by raducoravu** [comment] 2020-07-28 04:08
Thanks for registering an issue, we'll try to find some time to look into this. It's quite hard to generate valid DITA in such cases because a valid DITA document needs to have a title so we usually rely on the first title in the document to be the title of the DITA topic. In such cases you can perform some manual post process and we'll try to look on our side to fix this behavior.
What was your expected behavior in this case?

**Comment by DunaMariusCosmin** [comment] 2020-12-07 10:54
We added a fix for this problem, but this will be available in version 23.1 of Oxygen because it required some changes in the main application.

**Closed by DunaMariusCosmin** 2020-12-07 10:54 UTC

**Comment by DunaMariusCosmin** [comment] 2021-03-04 14:33
Hi,
I just wanted to let you know that Oxygen 23.1 is out now and it contains a fix for the issue you reported.
