### ISSUE TITLE
Error: Type ID must be an NCName

### ISSUE THREAD

**Issue by Tiemichael** [oxygenxml/oxygen-resources-converter#39] opened 2020-11-06 04:46 UTC
Thank you for providing this very helpful plugin!
When trying to convert a word-document (.docx) to .xml I get a lot of Errors: Type ID must be an NCName.

Looking at the source-document I see that these errors are caused by 2 reasons:
1) the document name contains a space e.g 'User Manual': this space is converted into '%20' - but '%' is not allowed inside a NCName (https://stackoverflow.com/a/6159003). 
2) Word-heading names including commas or dots eg. 'Settings (user, super-user, administrator)'  or 'How to open a .doc-document'. - also here according to  https://stackoverflow.com/a/6159003  commas and dots are not allowed.

While the first issues is easy to fix as it only occurs once, the second error can occur several times in the document.

Is there a way to fix this in the converter (eg. escaping certain characters) or is there a recommendation how to preprocess the document automatically.

Thanks!

**Comment by DunaMariusCosmin** [comment] 2020-11-06 17:18
Hi,
What conversion did you use: Word to DITA, Word to DocBook4  or Word to DocBook5? 
I was not able to reproduce the problem on my side. 
I created this simple word document, as you described: [User Manual.docx](https://github.com/oxygenxml/oxygen-resources-converter/files/5502528/User.Manual.docx) and the name of the document or the word-headings are not used as attributes' values in the converted document.
Could you attach a simple word document where the problem can be reproduced?

Best regards,
Cosmin

**Comment by Tiemichael** [comment] 2020-11-07 03:15
Thank you for looking into this issue!
I am using Word to DITA with Oxygen XML Editor 22.1
Attached is a very simple word document and a zip with the generated dita-files.
DITA validation shows the errors mentioned earlier for chapters marked Header2 (and Header3 and Header4)

Best regards
Michael
[dita.zip](https://github.com/oxygenxml/oxygen-resources-converter/files/5504229/dita.zip)
[USER MANUAL.docx](https://github.com/oxygenxml/oxygen-resources-converter/files/5504230/USER.MANUAL.docx)

**Comment by DunaMariusCosmin** [comment] 2020-11-09 10:28
I reproduced the problem using the sample you attached. We'll try to find some time to look into this. Until then you can use the "Find/Replace in Files" action from the contextual menu of the DMM view for replacing invalid character ("%20" with '_' and "," with ''). For this do the following steps for every replacement:
1. Open the converted map in the DMM view and invoke the "Find/Replace in Files" action from the contextual menu.
2. Fill in the "Restrict to XPath" field with '/topic/@id'.
3. Make sure that "Current DITA map hierarchy" is selected. 
4. Complete the "Text to find" and "Replace with" fields:
-  For Text to find: "%20" at first replacement and "," at second replacement
-  For Replace with: "_" at first replacement and let the field empty at the second one.
5. Press "Replace all" button.

**Comment by Tiemichael** [comment] 2020-11-10 02:36
Thank you very much for the detailed instructions
Highly appreciated!

**Comment by DunaMariusCosmin** [comment] 2020-12-07 10:52
We added a fix for this problem, but this will be available in version 23.1 of Oxygen because it required some changes in the main application.

**Closed by DunaMariusCosmin** 2020-12-07 10:52 UTC

**Comment by DunaMariusCosmin** [comment] 2021-03-05 09:50
Hello,
I just wanted to let you know that Oxygen 23.1 is out now and it contains a fix for the issue you reported on this thread.

Regards,
Cosmin
